//
//  HomeJustDropModel.swift
//  KREAM_CloneCoding
//
//  Created by 이수현 on 10/19/24.
//

import Foundation
import UIKit

struct HomeJustDropModel {
    var image : String
    var isSaved : Bool
    var dealCount : Float
    var title : String
    var subTitle : String
    var price : Int
    
    var simiarItemImage : [UIImage]
    var immediatelyPurchasePrice : Int
    var immediatelySellPrice : Int
    var savedCount : Int
    
    var expressedDeliveryPrice : Int
    var normalDeliveryPrice : Int
    var sizes : [[String : Int]]?
}

extension HomeJustDropModel {
    static func dummy() -> [HomeJustDropModel] {
        return [
            HomeJustDropModel(image: "https://img.29cm.co.kr/item/202402/11eec4bee07183cb91eb3bb3361e6c39.jpg?width=700",
                              isSaved: false,
                              dealCount: 23.5,
                              title: "Matin Kim Logo Coating Jumper",
                              subTitle: "마뗑킴 로고 코팅 점퍼 블랙",
                              price: 228000,
                              simiarItemImage: [.matinKim2, .matinKim3, .matinKim4, .matinKim5, .matinKim6, .matinKim7, .matinKim, .matinKim3, .matinKim7],
                              immediatelyPurchasePrice: 345000,
                              immediatelySellPrice: 396000,
                              savedCount: 2122,
                              expressedDeliveryPrice: 345000,
                              normalDeliveryPrice: 407000,
                              sizes: [["S" : 360000],
                                      ["M" : 120000],
                                      ["L" : 4230000],
                                      ["XL" : 123000],
                                      ["XXL" : 432500],
                                     ]
                             ),
            HomeJustDropModel(image: "https://img.danawa.com/prod_img/500000/842/688/img/17688842_1.jpg?shrink=330:*&_v=20220819131507",
                              isSaved: false,
                              dealCount: 12.8,
                              title: "MLB",
                              subTitle: "청키라이너 뉴욕양키스",
                              price: 139000,
                              simiarItemImage: [.MLB, .ad, .adidasBapeShoes, .deusJacket, .diamondRing, .halfHeadband, .femaleRecommend, .jordan, .halfHeadband],
                              immediatelyPurchasePrice: 345000,
                              immediatelySellPrice: 396000,
                              savedCount: 5122,
                              expressedDeliveryPrice: 345000,
                              normalDeliveryPrice: 407000,
                              sizes: [
                                      ["M" : 120000],
                                      ["XL" : 123000],
                                      ["XXL" : 432500],
                                     ]
                             ),
            HomeJustDropModel(image: "https://m.media-amazon.com/images/I/710ZYjabpvL._AC_SX695_.jpg",
                              isSaved: true,
                              dealCount: 15.6,
                              title: "Jordan",
                              subTitle: "Jordan 1 Retro High OG Yellow Ochre",
                              price: 228000,
                              simiarItemImage: [.MLB, .ad, .adidasBapeShoes, .deusJacket, .diamondRing, .halfHeadband,.femaleRecommend, .jordan, .halfHeadband],
                              immediatelyPurchasePrice: 345000,
                              immediatelySellPrice: 396000,
                              savedCount: 5122,
                              expressedDeliveryPrice: 345000,
                              normalDeliveryPrice: 407000,
                              sizes: [["S" : 360000],
                                      ["M" : 120000],
                                      ["L" : 4230000],
                                      ["XL" : 123000],
                                      ["XXL" : 432500],
                                     ]
                             ),
            
            HomeJustDropModel(image: "https://img.danawa.com/prod_img/500000/842/688/img/17688842_1.jpg?shrink=330:*&_v=20220819131507",
                              isSaved: true,
                              dealCount: 22.1,
                              title: "MLB2",
                              subTitle: "청키라이너 뉴욕양키스2",
                              price: 193000,
                              simiarItemImage: [.MLB, .ad, .adidasBapeShoes, .deusJacket, .diamondRing, .halfHeadband,.femaleRecommend, .jordan, .halfHeadband],
                              immediatelyPurchasePrice: 345000,
                              immediatelySellPrice: 396000,
                              savedCount: 5122,
                              expressedDeliveryPrice: 345000,
                              normalDeliveryPrice: 407000,
                              sizes: [["S" : 360000],
                                      ["M" : 120000],
                                      ["L" : 4230000],
                                      ["XL" : 123000],
                                      ["XXL" : 432500],
                                     ]
                             ),
            HomeJustDropModel(image: "https://kream-phinf.pstatic.net/MjAyMjA1MDNfNDcg/MDAxNjUxNTcxMzczNjY1.7_5uAFAC-O7LWDO8AmYuJxfhO6qwHNBopoci6A-1XzYg.EyYmxX6c0AUcpZQKIXC1OFym1fl9bRlZvmTso43Xqg8g.PNG/a_095f2500bc074b81867e777cf9ad8da0.png?type=l_webp",
                              isSaved: false,
                              dealCount: 11.6,
                              title: "아디다스",
                              subTitle: "Adidas Superstar Core Black White",
                              price: 88000,
                              simiarItemImage: [.MLB, .ad, .adidasBapeShoes, .deusJacket, .diamondRing, .halfHeadband,.femaleRecommend, .jordan, .halfHeadband],
                              immediatelyPurchasePrice: 98000,
                              immediatelySellPrice: 108000,
                              savedCount: 123,
                              expressedDeliveryPrice: 108000,
                              normalDeliveryPrice: 108000,
                              sizes: [["S" : 360000],
                                      ["M" : 120000],
                                      ["L" : 4230000],
                                      ["XL" : 123000],
                                      ["XXL" : 432500],
                                     ]
                             ),
            HomeJustDropModel(image: "https://kream-phinf.pstatic.net/MjAyMjA4MThfMjI5/MDAxNjYwNzk3NTE1OTgx.PIl1nZ-_EhAoytfkTem0L7vuNWvDise9DI1cPUSrK7Ag.xtPv15NnoMHGmygFr_n-5I_dt4UhWhK4IlPcmPHPaoYg.PNG/a_33ff4989dff04f66b485b0933136bb4e.png?type=l_webp",
                              isSaved: false,
                              dealCount: 51.1,
                              title: "Adidas Superstar Golden Beige",
                              subTitle: "아디다스 슈퍼스타 골든 베이지",
                              price: 199000,
                              simiarItemImage: [.MLB, .ad, .adidasBapeShoes, .deusJacket, .diamondRing, .halfHeadband,.femaleRecommend, .jordan, .halfHeadband],
                              immediatelyPurchasePrice: 345000,
                              immediatelySellPrice: 396000,
                              savedCount: 5122,
                              expressedDeliveryPrice: 345000,
                              normalDeliveryPrice: 407000,
                              sizes: [["S" : 360000],
                                      ["M" : 120000],
                                      ["L" : 4230000],
                                      ["XL" : 123000],
                                      ["XXL" : 432500],
                                     ]
                             ),
            HomeJustDropModel(image: "https://img.29cm.co.kr/item/202402/11eec4bee07183cb91eb3bb3361e6c39.jpg?width=700",
                              isSaved: false,
                              dealCount: 23.5,
                              title: "Matin Kim Logo Coating Jumper",
                              subTitle: "마뗑킴 로고 코팅 점퍼 블랙",
                              price: 228000,
                              simiarItemImage: [.matinKim2, .matinKim3, .matinKim4, .matinKim5, .matinKim6, .matinKim7, .matinKim, .matinKim3, .matinKim7],
                              immediatelyPurchasePrice: 345000,
                              immediatelySellPrice: 396000,
                              savedCount: 2122,
                              expressedDeliveryPrice: 345000,
                              normalDeliveryPrice: 407000,
                              sizes: [["S" : 360000],
                                      ["M" : 120000],
                                      ["L" : 4230000],
                                      ["XL" : 123000],
                                      ["XXL" : 432500],
                                     ]
                             ),
            HomeJustDropModel(image: "https://img.danawa.com/prod_img/500000/842/688/img/17688842_1.jpg?shrink=330:*&_v=20220819131507",
                              isSaved: false,
                              dealCount: 12.8,
                              title: "MLB",
                              subTitle: "청키라이너 뉴욕양키스",
                              price: 139000,
                              simiarItemImage: [.MLB, .ad, .adidasBapeShoes, .deusJacket, .diamondRing, .halfHeadband, .femaleRecommend, .jordan, .halfHeadband],
                              immediatelyPurchasePrice: 345000,
                              immediatelySellPrice: 396000,
                              savedCount: 5122,
                              expressedDeliveryPrice: 345000,
                              normalDeliveryPrice: 407000,
                              sizes: [
                                      ["M" : 120000],
                                      ["XL" : 123000],
                                      ["XXL" : 432500],
                                     ]
                             ),
            HomeJustDropModel(image: "https://m.media-amazon.com/images/I/710ZYjabpvL._AC_SX695_.jpg",
                              isSaved: true,
                              dealCount: 15.6,
                              title: "Jordan",
                              subTitle: "Jordan 1 Retro High OG Yellow Ochre",
                              price: 228000,
                              simiarItemImage: [.MLB, .ad, .adidasBapeShoes, .deusJacket, .diamondRing, .halfHeadband,.femaleRecommend, .jordan, .halfHeadband],
                              immediatelyPurchasePrice: 345000,
                              immediatelySellPrice: 396000,
                              savedCount: 5122,
                              expressedDeliveryPrice: 345000,
                              normalDeliveryPrice: 407000,
                              sizes: [["S" : 360000],
                                      ["M" : 120000],
                                      ["L" : 4230000],
                                      ["XL" : 123000],
                                      ["XXL" : 432500],
                                     ]
                             ),
            
            HomeJustDropModel(image: "https://img.danawa.com/prod_img/500000/842/688/img/17688842_1.jpg?shrink=330:*&_v=20220819131507",
                              isSaved: true,
                              dealCount: 22.1,
                              title: "MLB2",
                              subTitle: "청키라이너 뉴욕양키스2",
                              price: 193000,
                              simiarItemImage: [.MLB, .ad, .adidasBapeShoes, .deusJacket, .diamondRing, .halfHeadband,.femaleRecommend, .jordan, .halfHeadband],
                              immediatelyPurchasePrice: 345000,
                              immediatelySellPrice: 396000,
                              savedCount: 5122,
                              expressedDeliveryPrice: 345000,
                              normalDeliveryPrice: 407000,
                              sizes: [["S" : 360000],
                                      ["M" : 120000],
                                      ["L" : 4230000],
                                      ["XL" : 123000],
                                      ["XXL" : 432500],
                                     ]
                             ),
            HomeJustDropModel(image: "https://kream-phinf.pstatic.net/MjAyMjA1MDNfNDcg/MDAxNjUxNTcxMzczNjY1.7_5uAFAC-O7LWDO8AmYuJxfhO6qwHNBopoci6A-1XzYg.EyYmxX6c0AUcpZQKIXC1OFym1fl9bRlZvmTso43Xqg8g.PNG/a_095f2500bc074b81867e777cf9ad8da0.png?type=l_webp",
                              isSaved: false,
                              dealCount: 11.6,
                              title: "아디다스",
                              subTitle: "Adidas Superstar Core Black White",
                              price: 88000,
                              simiarItemImage: [.MLB, .ad, .adidasBapeShoes, .deusJacket, .diamondRing, .halfHeadband,.femaleRecommend, .jordan, .halfHeadband],
                              immediatelyPurchasePrice: 98000,
                              immediatelySellPrice: 108000,
                              savedCount: 123,
                              expressedDeliveryPrice: 108000,
                              normalDeliveryPrice: 108000,
                              sizes: [["S" : 360000],
                                      ["M" : 120000],
                                      ["L" : 4230000],
                                      ["XL" : 123000],
                                      ["XXL" : 432500],
                                     ]
                             ),
            HomeJustDropModel(image: "https://kream-phinf.pstatic.net/MjAyMjA4MThfMjI5/MDAxNjYwNzk3NTE1OTgx.PIl1nZ-_EhAoytfkTem0L7vuNWvDise9DI1cPUSrK7Ag.xtPv15NnoMHGmygFr_n-5I_dt4UhWhK4IlPcmPHPaoYg.PNG/a_33ff4989dff04f66b485b0933136bb4e.png?type=l_webp",
                              isSaved: false,
                              dealCount: 51.1,
                              title: "Adidas Superstar Golden Beige",
                              subTitle: "아디다스 슈퍼스타 골든 베이지",
                              price: 199000,
                              simiarItemImage: [.MLB, .ad, .adidasBapeShoes, .deusJacket, .diamondRing, .halfHeadband,.femaleRecommend, .jordan, .halfHeadband],
                              immediatelyPurchasePrice: 345000,
                              immediatelySellPrice: 396000,
                              savedCount: 5122,
                              expressedDeliveryPrice: 345000,
                              normalDeliveryPrice: 407000,
                              sizes: [["S" : 360000],
                                      ["M" : 120000],
                                      ["L" : 4230000],
                                      ["XL" : 123000],
                                      ["XXL" : 432500],
                                     ]
                             ),

        ]
    }
}
